# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed May 28 17:02:33 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(570, 505)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 531, 441))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayoutWidget = QtGui.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 11, 501, 121))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.txt_mr_n = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_mr_n.setObjectName(_fromUtf8("txt_mr_n"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_mr_n)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txt_mr_k = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_mr_k.setObjectName(_fromUtf8("txt_mr_k"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txt_mr_k)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.txt_mr_res = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_mr_res.setReadOnly(True)
        self.txt_mr_res.setObjectName(_fromUtf8("txt_mr_res"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txt_mr_res)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_mr_run = QtGui.QPushButton(self.formLayoutWidget)
        self.btn_mr_run.setObjectName(_fromUtf8("btn_mr_run"))
        self.horizontalLayout.addWidget(self.btn_mr_run)
        self.btn_mr_step = QtGui.QPushButton(self.formLayoutWidget)
        self.btn_mr_step.setObjectName(_fromUtf8("btn_mr_step"))
        self.horizontalLayout.addWidget(self.btn_mr_step)
        self.btn_mr_reset = QtGui.QPushButton(self.formLayoutWidget)
        self.btn_mr_reset.setObjectName(_fromUtf8("btn_mr_reset"))
        self.horizontalLayout.addWidget(self.btn_mr_reset)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(75, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(3, QtGui.QFormLayout.LabelRole, spacerItem)
        self.txt_mr_exec = QtGui.QPlainTextEdit(self.tab)
        self.txt_mr_exec.setGeometry(QtCore.QRect(10, 140, 501, 261))
        self.txt_mr_exec.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.txt_mr_exec.setObjectName(_fromUtf8("txt_mr_exec"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(9, 15, 501, 141))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.txt_pm_n = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.txt_pm_n.setObjectName(_fromUtf8("txt_pm_n"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_pm_n)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.txt_pm_b = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.txt_pm_b.setObjectName(_fromUtf8("txt_pm_b"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.txt_pm_b)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.txt_pm_it = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.txt_pm_it.setObjectName(_fromUtf8("txt_pm_it"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.txt_pm_it)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.btn_pm_run = QtGui.QPushButton(self.formLayoutWidget_2)
        self.btn_pm_run.setObjectName(_fromUtf8("btn_pm_run"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.btn_pm_run)
        self.txt_pm_res = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.txt_pm_res.setReadOnly(True)
        self.txt_pm_res.setObjectName(_fromUtf8("txt_pm_res"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.txt_pm_res)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(9, 9, 501, 131))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.txt_pg_size = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.txt_pg_size.setObjectName(_fromUtf8("txt_pg_size"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_pg_size)
        self.txt_pg_res = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.txt_pg_res.setReadOnly(True)
        self.txt_pg_res.setObjectName(_fromUtf8("txt_pg_res"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.txt_pg_res)
        self.btn_pg_run = QtGui.QPushButton(self.formLayoutWidget_3)
        self.btn_pg_run.setObjectName(_fromUtf8("btn_pg_run"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.btn_pg_run)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.actionA_propos = QtGui.QAction(MainWindow)
        self.actionA_propos.setObjectName(_fromUtf8("actionA_propos"))
        self.menuFichier.addAction(self.actionQuitter)
        self.menu.addAction(self.actionA_propos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuitter, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CryptAlgos", None))
        self.label.setText(_translate("MainWindow", "N", None))
        self.txt_mr_n.setText(_translate("MainWindow", "0", None))
        self.label_2.setText(_translate("MainWindow", "K", None))
        self.txt_mr_k.setText(_translate("MainWindow", "10", None))
        self.label_3.setText(_translate("MainWindow", "Result", None))
        self.btn_mr_run.setText(_translate("MainWindow", "Run", None))
        self.btn_mr_step.setText(_translate("MainWindow", "Step", None))
        self.btn_mr_reset.setText(_translate("MainWindow", "Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Miller Rabin", None))
        self.label_4.setText(_translate("MainWindow", "N", None))
        self.txt_pm_n.setText(_translate("MainWindow", "1", None))
        self.label_5.setText(_translate("MainWindow", "B", None))
        self.txt_pm_b.setText(_translate("MainWindow", "0", None))
        self.label_6.setText(_translate("MainWindow", "It", None))
        self.txt_pm_it.setText(_translate("MainWindow", "10", None))
        self.label_9.setText(_translate("MainWindow", "Result", None))
        self.btn_pm_run.setText(_translate("MainWindow", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Pm1 Pollard", None))
        self.label_7.setText(_translate("MainWindow", "Size", None))
        self.label_8.setText(_translate("MainWindow", "Result", None))
        self.txt_pg_size.setText(_translate("MainWindow", "1", None))
        self.btn_pg_run.setText(_translate("MainWindow", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Prime Gen", None))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier", None))
        self.menu.setTitle(_translate("MainWindow", "?", None))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter", None))
        self.actionA_propos.setText(_translate("MainWindow", "A propos", None))

